application: donaldknuthcollege
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /administratie(/.*)?
  script: admin.py

- url: .*
  script: main.py
  login: admin